# 开发环境
server:
  # 服务端口
  port: 8005

# 数据库连接
spring:
  application:
    name: service-mail
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848
  jackson:
    time-zone: GMT+8
    # 后台数据库中的时间是这种 "2019-11-11 16:26:26" 但是通过从数据库查出来后, 通过json格式返回至前端
    # 时间就变成这样了 "2019-11-15T13:47:27.000+0000"
    # 可以配置该属性来控制格式 spring.jackson.date-format
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 110.42.250.118 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: 20peng #Redis密码
    database: 0 #Redis数据库索引 (默认为0)
    timeout: 1800000 #连接超时时间 (毫秒)
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数 (使用负值表示没有限制)
        max-wait: -1 #最大阻塞等待时间 (负数表示没限制)
        max-idle: 5 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

feign:
  client:
    config:
      default:
        # 在Feign客户端调用服务端的时候, 很容易出现连接超时的错误, 默认最长的请求时间为1s超过一秒就会报错
        # feign.RetryableException: Read timed out executing DELETE
        # 此处就是说 连接时间 和 啥时间 设置为 5 秒
        connect-timeout: 5000
        read-timeout: 5000
  hystrix:
    # 开启 熔断机制 (hystrix熔断器)  (如果开启了 hystrix熔断器, 那么 使用 @FeignClient(name = "service-oss") 远程调用的类 就必须定义 熔断后的方法)
    # com.netflix.hystrix.exception.HystrixRuntimeException: OssClient#uploadOssFile(MultipartFile) failed and no fallback available.
    enabled: false

